#Zian Kang, Homework 3: Objects & Graphics : draw a house

from graphics import *

def main():
    win = GraphWin("House", 500, 500)
    message = Text(Point(250, 450),"Click on lower left corner of the house frame.")
    message.draw(win)
    p1 = win.getMouse()
    message.setText("Click upper right corner of the house frame.")
    p2 = win.getMouse()
    r1 = Rectangle(p1,p2)
    r1.draw(win)
    p1x = p1.getX()
    p1y = p1.getY()
    p2x = p2.getX()
    p2y = p2.getY()
    message.setText("Click on the center of the top of the door.")
    p3 = win.getMouse()
    p3x = p3.getX()
    p3y = p3.getY()
    p4 = Point(p3x - (p2x - p1x) / 10, p3y)
    p5 = Point(p3x + (p2x - p1x) / 10, p1y)
    r2 = Rectangle(p4,p5)
    r2.draw(win)
    p6 = Point(p3x + (p2x - p1x) / 10 - 15, (p1y + p3y) / 2)
    c1 = Circle(p6,10)
    c1.draw(win)
    message.setText("Click on the center of the window.")
    p7 = win.getMouse()
    p7x = p7.getX()
    p7y = p7.getY()
    p8 = Point(p7x - (p2x - p1x) *3 / 40, p7y + (p2x - p1x) *3 / 40)
    p9 = Point(p7x + (p2x - p1x) *3 / 40, p7y - (p2x - p1x) *3 / 40)
    r3 = Rectangle(p8,p9)
    r3.draw(win)
    p10 = Point(p7x - (p2x - p1x) *3 / 40, p7y)
    p11 = Point(p7x + (p2x - p1x) *3 / 40, p7y)
    p12 = Point(p7x,p7y - (p2x - p1x) *3 / 40)
    p13 = Point(p7x,p7y + (p2x - p1x) *3 / 40)
    l1 = Line(p10,p11)
    l2 = Line(p12,p13)
    l1.draw(win)
    l2.draw(win)
    message.setText("Click on the peak of the roof.")
    p14 = win.getMouse()
    l3 = Line(p14, Point(p1x,p2y))
    l4 = Line(p14, p2)
    l3.draw(win)
    l4.draw(win)
    win.getMouse()
    win.close()    

if __name__ == '__main__':
    main()